spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # path to config properties
          uri: D:/ForwardSource/spring-cloud-learning
          search-paths: config-repository

server:
  port: 7001