spring:
  application:
    name: hello-service

server:
  port: 7111
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  