spring:
  application:
    name: ribbon-service

server:
  port: 7212

eureka:
  instance:
      hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/