spring:
  application:
    name: zuul-gateway

server:
  port: 5555

zuul:
  routes:
    ribbon-service:
      path: /ribbon-service/**
      serviceId: ribbon-service
    feign-service:
      path: /feign-service/**
      serviceId: feign-service

eureka:
  instance:
        hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
